version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    links:
      - explorer_frontend
    networks:
      explorer_net:
        ipv4_address: 172.28.1.1

  signet:
    restart: unless-stopped
    image: kallewoof/signet:0.20
    environment:
      BITCOIN_NETWORK: signet
      BITCOIN_EXTRA_ARGS: |-
        rpcport=43782
        rpcallowip=0.0.0.0/0
        rpcbind=0.0.0.0:43782
        port=39388
        whitelist=0.0.0.0/0
        zmqpubrawblock=tcp://0.0.0.0:28332
        zmqpubrawtx=tcp://0.0.0.0:28333
    ports: 
      - 43782:43782
    expose:
      - "43782" # RPC
      - "39388" # P2P
      - "28332" # ZMQ
      - "28333" # ZMQ
    volumes:
      - $HOME/bitcoin_datadir:/root/.bitcoin
    networks:
      explorer_net:
        ipv4_address: 172.28.1.2

  explorer_backend:
    image: kallewoof/signet-explorer-backend:0.18
    ports:
      - 4000:4000
    expose:
      - "4000" # electrs API
    volumes:
      - $HOME/bitcoin_datadir:/root/.bitcoin
    command: electrs -vvv --timestamp --daemon-dir /root/.bitcoin --daemon-rpc-addr 172.28.1.2:43782 --network signet --http-addr 0.0.0.0:4000
    links:
      - signet
    networks:
      explorer_net:
        ipv4_address: 172.28.1.3

  explorer_frontend:
    image: kallewoof/signet-explorer-frontend:0.18
    ports:
      - 5000:5000
    expose:
      - "5000" # explorer web UI
    environment:
      PORT: 5000
      API_URL: http://localhost/api/
      NATIVE_ASSET_LABEL: sBTC
      SITE_TITLE: Signet Block Explorer
      SITE_DESC: Esplora Signet Block Explorer
    command: npm run dev-server
    links:
      - explorer_backend
    networks:
      explorer_net:
        ipv4_address: 172.28.1.4

networks:
  explorer_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
